version: 2

models:
  - name: MarketChanges(1)
    description: "For the market messages"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: MarketInformation(2)
    description: "For information on the markets"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
